################################################################################
MLI_FILE		= cordova_fcm.mli
## Name which will be used in -package with ocamlfind
LIB_NAME		= cordova-plugin-fcm
################################################################################
